class Constants(object):
    API_VERSION_QUERY_PARAM_NAME = 'api-version'
    OUTPUT_TYPE_QUERY_PARAM_NAME = 'output-type'
    AUTHORIZATION_HEADER = 'Authorization'
    API_KEY_HEADER = 'api-key'
    BEARER_TOKEN_PREFIX = 'Bearer '
    DEFAULT_SUBSCRIPTION_ID = 'default'
    HTTP_CONTENT_TYPE_ZIP = 'application/zip'
    HTTP_CONTENT_TYPE_JSON = 'application/json'
    HTTP_CONTENT_TYPE_HEADER_NAME = 'Content-Type'
    PREDECESSOR_OP_ID_NA = 'na'
    AML_PIPELINE_RUN_TYPE = 'azureml.PipelineRun'
    AML_SCRIPT_RUN_TYPE = 'azureml.scriptrun'
    OPERATION_STATUS_PARAMETER_NAME = 'status'